export enum AuditActionEnum {
  SANCTIONED_ENTITY_CREATED = 'SANCTIONED_ENTITY_CREATED',
  SANCTIONED_ENTITY_STATUS_CHANGED = 'SANCTIONED_ENTITY_STATUS_CHANGED',
  SANCTIONED_ENTITY_REMOVED = 'SANCTIONED_ENTITY_REMOVED',
  REVIEW_CREATED = 'REVIEW_CREATED',
}
