export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  ACCOUNTS = 'ACCOUNTS',
  COMPLIANCE = 'COMPLIANCE',
  AUDITOR = 'AUDITOR',
  ANALYST = 'ANALYST',
  VERIFICATION = 'VERIFICATION',
  DATA_ENTRY = 'DATA_ENTRY',
}
